package net.goldenstack.loot;

import org.jetbrains.annotations.NotNull;

/**
 * Generates numbers based on provided loot contexts.
 */
public interface LootNumber {

    /**
     * Generates a long depending on the information in the provided context.<br>
     * This is an explicitly impure method—it depends on state outside the given context.
     * @param context the context object, to use if required
     * @return the long generated by this loot number for the provided context
     */
    long getLong(@NotNull LootContext context);

    /**
     * Generates a double depending on the information in the provided context.<br>
     * This is an explicitly impure method—it depends on state outside the given context.
     * @param context the context object, to use if required
     * @return the double generated by this loot number for the provided context
     */
    double getDouble(@NotNull LootContext context);

}
