package dev.goldenstack.loot;

import dev.goldenstack.loot.context.LootContext;
import net.minestom.server.item.ItemStack;
import org.jetbrains.annotations.NotNull;

import java.util.List;

/**
 * A loot choice that can be generated by a {@link dev.goldenstack.loot.entry.LootEntry}.
 */
public interface LootChoice {

    /**
     * Gets the weight for this LootChoice based on the provided luck.
     */
    int getWeight(float luck);

    /**
     * Generates a list of items as loot based on the provided context.
     */
    @NotNull List<ItemStack> generateLoot(@NotNull LootContext context);
}

